#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

event_templates($_,
		'/etc/dnsmasq.conf',
		'/etc/ethers',
		'/etc/hosts',
		'/etc/resolv.conf') foreach (qw(
  nethserver-dnsmasq-update
  nethserver-dnsmasq-uninstall
));

# conf BEFORE expand templates, to read db default values - Refs #1059
event_actions('nethserver-dnsmasq-update',
	      'initialize-default-databases' => '00',
	      'nethserver-dnsmasq-conf' => '05',
	      'firewall-adjust' => '30',
	      'runlevel-adjust' => '40');

event_actions('nethserver-dnsmasq-uninstall',
	      'nethserver-dnsmasq-uninstall' => '20',
	      'firewall-adjust' => '40',
	      'runlevel-adjust' => '50');

foreach (qw(
    host-create 
    host-delete 
    host-modify 
    nethserver-dnsmasq-update
)) {
    event_templates($_,
		    '/etc/ethers',
		    '/etc/hosts');

    safe_symlink("reload", 'root/etc/e-smith/events/' . $_ . '/services2adjust/dnsmasq');
}

#--------------------------------------------------
# actions for dhcp-reservation validator
#--------------------------------------------------
my $validator = 'dhcp-reservation';
validator_link("ip-not-reserved-local", $validator, "20");
