#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
use esmith::Build::CreateLinks  qw(:all);

event_templates($_, qw(
		/etc/dnsmasq.conf
		/etc/resolv.conf
		/etc/dnsmasq-dhcp-hosts
		/etc/ppp/options.xl2tpd
)) foreach (qw(
  nethserver-dnsmasq-update
));


# conf BEFORE expand templates, to read db default values - Refs #1059
event_actions('nethserver-dnsmasq-update',
	      'initialize-default-databases' => '00',
	      'nethserver-dnsmasq-conf' => '02');

event_services('nethserver-dnsmasq-update',
	       'dnsmasq' => 'restart');

#
# Reload config whenever HostsDB changes
#
foreach (qw(
    host-create 
    host-delete 
    host-modify 
)) {
    event_services($_, qw(
       dnsmasq reload
    ));
    event_templates($_, qw(
       /etc/dnsmasq-dhcp-hosts
    ));
}


#--------------------------------------------------
# actions for dhcp-reservation validator
#--------------------------------------------------
validator_actions('dhcp-reservation',
		  'ip-not-reserved-local' => '20',
		  'ip-mac-address' => '30',
		  'mac-not-reserved' => '40',
    );


#--------------------------------------------------
# nethserver-dnsmasq-save event
#--------------------------------------------------
event_templates('nethserver-dnsmasq-save', qw(
		/etc/dnsmasq.conf
		/etc/ppp/options.xl2tpd
));
event_services('nethserver-dnsmasq-save',
	       'dnsmasq' => 'restart');

#--------------------------------------------------
# nethserver-hosts-save event
#--------------------------------------------------
event_templates('nethserver-hosts-save', qw(
		/etc/dnsmasq.conf
		/etc/ppp/options.xl2tpd
));
event_services('nethserver-hosts-save',
	       'dnsmasq' => 'restart');

#--------------------------------------------------
# actions for interface-update event
#--------------------------------------------------
event_templates('interface-update',
                '/etc/dnsmasq.conf');
event_services('interface-update',
	       'dnsmasq' => 'restart');

#--------------------------------------------------
# actions for migration-import event
#--------------------------------------------------

$event = "migration-import";
event_actions($event, 'nethserver-dnsmasq-migrate' => 60);

