#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);


#--------------------------------------------------
# actions for bootstrap-console-save event
#--------------------------------------------------
$event = "bootstrap-console-save";

templates2events("/etc/dnsmasq.conf", $event);
templates2events("/etc/dnsmasq.d/dhcp.conf", $event);
templates2events("/etc/dnsmasq.d/dns.conf", $event);
templates2events("/etc/resolv.conf", $event);
event_link("conf-hostsdb", $event , "03");
event_link("purge-domain", $event, "04");

##--------------------------------------------------
## actions for console-save event
##--------------------------------------------------
$event = "console-save";

event_link("conf-hostsdb", $event , "04");

#--------------------------------------------------
# actions for remoteaccess-update event
#--------------------------------------------------

$event = "remoteaccess-update";

safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/dnsmasq");

#--------------------------------------------------
# actions for update event
# --------------------------------------------------

$event = "nethserver-dnsmasq-update";

safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/dnsmasq");
templates2events("/etc/dnsmasq.conf", $event);
templates2events("/etc/dnsmasq.d/dhcp.conf", $event);
templates2events("/etc/dnsmasq.d/dns.conf", $event);
templates2events("/etc/resolv.conf", $event);


#--------------------------------------------------
# actions for save event
# --------------------------------------------------

$event = "nethserver-dnsmasq-save";

safe_symlink("reload", "root/etc/e-smith/events/$event/services2adjust/dnsmasq");
templates2events("/etc/dnsmasq.conf", $event);
templates2events("/etc/dnsmasq.d/dhcp.conf", $event);
templates2events("/etc/dnsmasq.d/dns.conf", $event);
templates2events("/etc/resolv.conf", $event);



foreach $event ( qw(host-create host-delete host-modify) )
{
    safe_symlink("reload", "root/etc/e-smith/events/$event/services2adjust/dnsmasq");
    templates2events("/etc/hosts", $event);
}


##--------------------------------------------------
## actions for domain-create event
##--------------------------------------------------
$event = "domain-create";
#
event_link("create-default-hosts", $event, "04");
templates2events("/etc/hosts", $event);
safe_symlink("reload", "root/etc/e-smith/events/$event/services2adjust/dnsmasq");

##--------------------------------------------------
## actions for domain-delete event
##--------------------------------------------------
$event = "domain-delete";

event_link("purge-domain", $event, "04");
templates2events("/etc/hosts", $event);
safe_symlink("reload", "root/etc/e-smith/events/$event/services2adjust/dnsmasq");

