#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package NethServer::Firewall;

use strict;
use esmith::ConfigDB;
use esmith::NetworksDB;
my $ndb = esmith::NetworksDB->open_ro();
my $cdb = esmith::ConfigDB->open('dhcp');
my %ifaces;

foreach ($ndb->interfaces()) {
    my $role = $_->prop('role') || next;
    if ($role eq 'green' || $role eq 'blue') { 
        $ifaces{$_->key} = '';
    }
}

# Delete ranges associated to non-existing blue or green interface
foreach ( $cdb->get_all_by_prop('type' => 'range') ) {
    if (!exists($ifaces{$_->key})) {
        $_->delete;    
    }
}
