#!/usr/bin/perl

#
# NethServer 
#
# Copyright (C) 2012 Nethesis srl
#

use strict;
use esmith::ConfigDB;
use NethServer::Service;

my $event = shift;

my $DB = esmith::ConfigDB->open();

#
# Set dns role to resolver if dnsmasq is enabled and current role
# is "none". Refs #1040 #1041
#
# Otherwise if role is "resolver" demote to "none" - Refs #1059
#
my $role = $DB->get_prop('dns', 'role');
my $status = $DB->get_prop('dnsmasq', 'status');

if($status eq 'enabled' && $role eq 'none') {
    $DB->set_prop('dns', 'role', 'resolver');
} elsif ($status ne 'enabled' && $role eq 'resolver') {
    $DB->set_prop('dns', 'role', 'none');
}

NethServer::Service::manage_add('nethserver-dnsmasq',
				'dnsmasq');
