#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::ConfigDB;
use NethServer::Service;

my $event = shift;

my $DB = esmith::ConfigDB->open();

#
# Set dns role to resolver if dnsmasq is enabled and current role
# is "none". Refs #1040 #1041
#
# Otherwise if role is "resolver" demote to "none" - Refs #1059
#
my $role = $DB->get_prop('dns', 'role');
my $status = $DB->get_prop('dnsmasq', 'status');

if($status eq 'enabled' && $role eq 'none') {
    $DB->set_prop('dns', 'role', 'resolver');
} elsif ($status ne 'enabled' && $role eq 'resolver') {
    $DB->set_prop('dns', 'role', 'none');
}

