#!/usr/bin/perl

#
# ip-mac-address -- check if the given ip is bounded to the given mac address
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use esmith::util;

my $mac = shift || die('Invalid MAC argument');
my $ip = shift || die('Invalid IP argument');

# Redirect ping output to /dev/null
open(my $oldout, '>&STDOUT') || die('Could not dup STDOUT: $!');
open(STDOUT, '>', '/dev/null');
my $reachable = system('/bin/ping', '-w', '2', $ip) == 0;
open(STDOUT, '>&', $oldout);

if( ! $reachable ) {
    exit 0; # nothing to do
}

my $octet = '[0-9a-fA-F]{2}';
my $bound = (split(/ +/, qx(/sbin/ip neigh show $ip)))[4];

if( $bound =~ m/$octet(:$octet){5}/i && $bound ne lc($mac) ) {
    exit 1;
}

exit 0;

