#!/usr/bin/perl -w
package esmith;

use strict;
use esmith::ConfigDB;
use esmith::util;

my $ip = shift || "";
exit 1 unless ($ip ne "");

my $db = esmith::ConfigDB->open_ro() or exit 1;

exit (not_in_dhcp_range($ip) || not_taken($ip) || must_be_local($ip));

sub not_in_dhcp_range
{
    my $address = shift;
    my $status = $db->get('dnsmasq')->prop('status') || "disabled";
    return 0 unless $status eq "enabled";
    my $start = $db->get('dnsmasq')->prop('DhcpRangeStart');
    my $end = $db->get('dnsmasq')->prop('DhcpRangeEnd');
    if (esmith::util::IPquadToAddr($start)
        <= esmith::util::IPquadToAddr($address)
        &&
        esmith::util::IPquadToAddr($address)
        <= esmith::util::IPquadToAddr($end))
    {
        print "valid_range\n";
        return 1; 
    }
    return 0;
}

sub not_taken
{
    my $checkIp = shift;

    my @takenList = map { defined $_ ? $_ : () } ('127.0.0.1',
				$db->get_prop('InternalInterface', 'IPAddress'),
				$db->get_value('GatewayIP'),
				$db->get_prop('ExternalInterface', 'IPAddress')
    );
    
    # XXX: we can check if IP is in use. Having MAC address:
    # ip neigh show $checkIp - Refs #1057

    if ( grep { $checkIp eq $_ } @takenList ) {
	print "valid_taken\n";
	return 1;
    }

    return 0;
}

sub must_be_local
{
    my $localip = shift;

    # Make sure that the IP is indeed local.
    my $ndb = esmith::NetworksDB->open_ro;
    my @local_list = $ndb->local_access_spec;

    foreach my $spec (@local_list)
    {
        next if $spec eq '127.0.0.1';
        if (Net::IPv4Addr::ipv4_in_network($spec, $localip))
        {
            return 0;
        }
    }
    # Not OK. The IP is not on any of our local networks.
    print "valid_local\n";
    return 1;
}
