#!/usr/bin/perl -w

use strict;
use esmith::ConfigDB;
use esmith::util;

my $mac = shift || die("Missing MAC argument");
my $ip = shift || die("Missing IP argument");

my $db = esmith::ConfigDB->open_ro() or die("Could not open Config DB");

sub is_reserved_ip
{
    my $checkIp = shift;

    my @takenList = map { defined $_ ? $_ : () } ('127.0.0.1',
				$db->get_prop('InternalInterface', 'IPAddress'),
				$db->get_value('GatewayIP'),
				$db->get_prop('ExternalInterface', 'IPAddress')
    );
    
    if ( grep { $checkIp eq $_ } @takenList ) 
    {
	return 1; # false
    }

    return 0; # true
}

sub is_local_ip
{
    my $localip = shift;

    # Make sure that the IP is indeed local.
    my $ndb = esmith::NetworksDB->open_ro;
    my @local_list = $ndb->local_access_spec;

    foreach my $spec (@local_list)
    {
        next if $spec eq '127.0.0.1';
        if (Net::IPv4Addr::ipv4_in_network($spec, $localip))
        {
            return 1;
        }
    }
    # Not OK. The IP is not on any of our local networks.
    return 0;
}

#
# Fail, if ip is reserved or is not in local networks
#
if(is_reserved_ip($ip)) 
{
    exit 3;
} 
elsif( ! is_local_ip($ip)) 
{
    exit 4;
}

# Success
exit 0;
