#!/usr/bin/perl

#
# ip-mac-address -- check if the given ip is bounded to the given mac address
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use esmith::util;
use esmith::HostsDB;

my $mac = shift || die('Invalid MAC argument');
my $key = shift || die('Invalid key argument');
my $ip = pop || die('Invalid IP argument');


my $db = esmith::HostsDB->open_ro();
foreach ($db->get_all_by_prop('type' => 'local')) {
    if($_->key eq $key) {
        next;
    }
    my $used_mac = $_->prop('MacAddress');
    my $used_ip = $_->prop('IpAddress');
    if ($used_mac eq $mac && $used_ip ne $ip) {
        exit 1;
    }
}
    

exit 0;

